services:
  main:
    container_name: main_prod
    build:
      context: .
      dockerfile: Dockerfile.prod
    env_file:
      - .prod.env
    ports:
      - 5000:5000
    command: npm run start:prod
    depends_on:
      - postgres
      - redis
    restart: always
  redis:
    image: 'redis:alpine'
    ports:
      - 6379:6379
  deathmatch_db:
    image: postgres:15.2
    env_file:
      - .prod.env
    environment:
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: always
  pgadmin:
    container_name: pg_admin
    image: dpage/pgadmin4
    env_file:
      - .dev.env
    ports:
      - 5050:80
volumes:
  pgdata: