export enum Env {
    NODE_ENV = 'NODE_ENV',
    PORT = 'PORT',
    POSTGRES_HOST = 'POSTGRES_HOST',
    POSTGRES_PORT = 'POSTGRES_PORT',
    POSTGRES_USER = 'POSTGRES_USER',
    POSTGRES_PASSWORD = 'POSTGRES_PASSWORD',
    POSTGRES_DB = 'POSTGRES_DB',
    GWT_SECRET = 'GWT_SECRET',
    REDIS_PORT = 'REDIS_PORT',
    REDIS_HOST = 'REDIS_HOST',
}
